# Generated by Django 4.2.13 on 2024-06-29 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blog_blogauthor_blogcomment_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
