# Generated by Django 4.2.13 on 2024-06-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogauthor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Author',
            new_name='author',
        ),
    ]
